name: CI

on:
  pull_request:
  push:
    branches: [ main, ci ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips42 libvips-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --retry 3

      - name: Linting
        run: bundle exec rubocop

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec